/** 基本信息页下拉选项（截图版字段） */

export const PROFILE_ETHNICITY_OPTIONS = [
  { value: "han", label: "汉族" },
  { value: "mongol", label: "蒙古族" },
  { value: "hui", label: "回族" },
  { value: "tibetan", label: "藏族" },
  { value: "uyghur", label: "维吾尔族" },
  { value: "miao", label: "苗族" },
  { value: "yi", label: "彝族" },
  { value: "zhuang", label: "壮族" },
  { value: "manchu", label: "满族" },
  { value: "tujia", label: "土家族" },
  { value: "buyei", label: "布依族" },
  { value: "dong", label: "侗族" },
  { value: "yao", label: "瑶族" },
  { value: "korean_cn", label: "朝鲜族" },
  { value: "bai", label: "白族" },
  { value: "hani", label: "哈尼族" },
  { value: "li", label: "黎族" },
  { value: "kazakh", label: "哈萨克族" },
  { value: "dai", label: "傣族" },
  { value: "she", label: "畲族" },
  { value: "lisu", label: "傈僳族" },
  { value: "gelao", label: "仡佬族" },
  { value: "lahu", label: "拉祜族" },
  { value: "va", label: "佤族" },
  { value: "shui", label: "水族" },
  { value: "naxi", label: "纳西族" },
  { value: "qiang", label: "羌族" },
  { value: "du", label: "土族" },
  { value: "mulam", label: "仫佬族" },
  { value: "xibe", label: "锡伯族" },
  { value: "kirgiz", label: "柯尔克孜族" },
  { value: "daur", label: "达斡尔族" },
  { value: "jingpo", label: "景颇族" },
  { value: "salar", label: "撒拉族" },
  { value: "blang", label: "布朗族" },
  { value: "maonan", label: "毛南族" },
  { value: "tajik", label: "塔吉克族" },
  { value: "pumi", label: "普米族" },
  { value: "acha", label: "阿昌族" },
  { value: "nu", label: "怒族" },
  { value: "evenki", label: "鄂温克族" },
  { value: "gin", label: "京族" },
  { value: "deang", label: "德昂族" },
  { value: "uzbek_cn", label: "乌孜别克族" },
  { value: "russian_cn", label: "俄罗斯族" },
  { value: "yugu", label: "裕固族" },
  { value: "bonan", label: "保安族" },
  { value: "menba", label: "门巴族" },
  { value: "oro", label: "鄂伦春族" },
  { value: "hezhen", label: "赫哲族" },
  { value: "monba", label: "珞巴族" },
  { value: "jino", label: "基诺族" },
  { value: "other", label: "其他" },
] as const;

export const PROFILE_POLITICAL_STATUS_OPTIONS = [
  { value: "cpc_member", label: "中共党员" },
  { value: "cpc_probation", label: "中共预备党员" },
  { value: "democratic_party", label: "民主党派" },
  { value: "non_party", label: "无党派人士" },
  { value: "youth_league", label: "共青团员" },
  { value: "masses", label: "群众" },
] as const;

/** 单位层级（截图） */
export const PROFILE_UNIT_LEVEL_OPTIONS = [
  { value: "central", label: "中央" },
  { value: "provincial", label: "省部级" },
  { value: "bureau", label: "厅局级" },
  { value: "county", label: "处级" },
  { value: "section", label: "科级" },
  { value: "below_county", label: "县级以下" },
  { value: "unit_local", label: "本单位" },
  { value: "other", label: "其他" },
] as const;

/** 行业划分（常用示例，可后续接字典） */
export const PROFILE_INDUSTRY_DIVISION_OPTIONS = [
  { value: "edu", label: "教育" },
  { value: "research", label: "科学研究" },
  { value: "health", label: "卫生" },
  { value: "engineering", label: "工程技术" },
  { value: "agri", label: "农业" },
  { value: "finance", label: "金融" },
  { value: "culture", label: "文化" },
  { value: "gov", label: "机关事业" },
  { value: "enterprise", label: "企业" },
  { value: "other", label: "其他" },
] as const;

export const PROFILE_TITLE_SERIES_OPTIONS = [
  { value: "edu_research", label: "高校教师/自然科学" },
  { value: "edu_social", label: "高校教师/哲学社会科学" },
  { value: "technical", label: "工程/工艺美术" },
  { value: "health_tech", label: "卫生技术" },
  { value: "economics", label: "经济" },
  { value: "accounting", label: "会计" },
  { value: "skill", label: "技能人员" },
  { value: "other", label: "其他" },
] as const;

export const PROFILE_TITLE_RANK_OPTIONS = [
  { value: "senior_chief", label: "正高级" },
  { value: "associate_senior", label: "副高级" },
  { value: "intermediate", label: "中级" },
  { value: "primary", label: "初级" },
  { value: "senior_tech", label: "高级技师" },
  { value: "technician", label: "技师" },
  { value: "senior_worker", label: "高级工" },
  { value: "none", label: "无" },
] as const;
